### ISSUE TITLE
Why is the Text Schlachter and the link ELB on the demos?

### ISSUE THREAD

**Issue by lustremedia** [renehamburger/blinx.js#93]
Is that due to copyright issues? Also on the one demo the link to the getbible api is broken points to here: https://getbible.net/v2/

Thanks for that library looking forward to integrate it.

**Comment by renehamburger** [comment]
Hi @lustremedia,

The Schlachter translation from 1951 is the most recent German Bible translation that is available for free via the getBible API. In comparison, the Elberfelder on that API is quite old in terms of its language. That's why I use Schlachter 1951 by default for German.
On the other hand, the online Bible I link to doesn't have the Schlachter 1951 but only the Schlachter 2000, which moved away from the generally accepted Greek NT text to something close to the Textus Receptus. That's why I didn't want to link to the Schlachter 2000 but chose the Elberfelder by default for German.

Thanks for pointing out the faulty link. It took me while to find out which one you meant. 😃 I kept checking the API requests, but these were all fine. Will fix that now.

**Comment by lustremedia** [comment]
Yeah sorry should have been more specific.  => "Link in the footer!" ^^
